In [14]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import pandas as pd

load_dotenv

connection_string = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}"
print("Starting the connection...")
engine = create_engine(connection_string, isolation_level="AUTOCOMMIT")
engine.connect()
print("Connected successfully!")

Starting the connection...
Connected successfully!

In [15]:
if engine is None:
    exit()

In [16]:
engine

Engine(postgresql://leo:***@localhost/db)

In [17]:
with engine.connect() as connection:
    connection.execute(text("""
        CREATE TABLE publishers(
        publisher_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        PRIMARY KEY(publisher_id)
    );
    CREATE TABLE authors(
        author_id INT NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        middle_name VARCHAR(50) NULL,
        last_name VARCHAR(100) NULL,
        PRIMARY KEY(author_id)
    );
    CREATE TABLE books(
        book_id INT NOT NULL,
        title VARCHAR(255) NOT NULL,
        total_pages INT NULL,
        rating DECIMAL(4, 2) NULL,
        isbn VARCHAR(13) NULL,
        published_date DATE,
        publisher_id INT NULL,
        PRIMARY KEY(book_id),
        CONSTRAINT fk_publisher FOREIGN KEY(publisher_id) REFERENCES publishers(publisher_id)
    );
    CREATE TABLE book_authors (
        book_id INT NOT NULL,
        author_id INT NOT NULL,
        PRIMARY KEY(book_id, author_id),
        CONSTRAINT fk_book FOREIGN KEY(book_id) REFERENCES books(book_id) ON DELETE CASCADE,
        CONSTRAINT fk_author FOREIGN KEY(author_id) REFERENCES authors(author_id) ON DELETE CASCADE
    
        );
        """))

ProgrammingError: (psycopg2.errors.DuplicateTable) relation "publishers" already exists

[SQL:
        CREATE TABLE publishers(
        publisher_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        PRIMARY KEY(publisher_id)
    );
    CREATE TABLE authors(
        author_id INT NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        middle_name VARCHAR(50) NULL,
        last_name VARCHAR(100) NULL,
        PRIMARY KEY(author_id)
    );
    CREATE TABLE books(
        book_id INT NOT NULL,
        title VARCHAR(255) NOT NULL,
        total_pages INT NULL,
        rating DECIMAL(4, 2) NULL,
        isbn VARCHAR(13) NULL,
        published_date DATE,
        publisher_id INT NULL,
        PRIMARY KEY(book_id),
        CONSTRAINT fk_publisher FOREIGN KEY(publisher_id) REFERENCES publishers(publisher_id)
    );
    CREATE TABLE book_authors (
        book_id INT NOT NULL,
        author_id INT NOT NULL,
        PRIMARY KEY(book_id, author_id),
        CONSTRAINT fk_book FOREIGN KEY(book_id) REFERENCES books(book_id) ON DELETE CASCADE,
        CONSTRAINT fk_author FOREIGN KEY(author_id) REFERENCES authors(author_id) ON DELETE CASCADE

        );
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [18]:
with engine.connect() as connection:
        connection.execute(text("""
        INSERT INTO publishers (publisher_id, name) VALUES
        (1, 'O Reilly Media'),
        (2, 'A Book Apart'),
        (3, 'A K PETERS'),
        (4, 'Academic Press'),
        (5, 'Addison Wesley'),
        (6, 'Albert&Sweigart'),
        (7, 'Alfred A. Knopf')
    ON CONFLICT (publisher_id) DO NOTHING;
    INSERT INTO authors (author_id, first_name, middle_name, last_name) VALUES
        (1, 'Merritt', NULL, 'Eric'),
        (2, 'Linda', NULL, 'Mui'),
        (3, 'Alecos', NULL, 'Papadatos'),
        (4, 'Anthony', NULL, 'Molinaro'),
        (5, 'David', NULL, 'Cronin'),
        (6, 'Richard', NULL, 'Blum'),
        (7, 'Yuval', 'Noah', 'Harari'),
        (8, 'Paul', NULL, 'Albitz')
    ON CONFLICT (author_id) DO NOTHING;
    INSERT INTO books (book_id, title, total_pages, rating, isbn, published_date, publisher_id) VALUES 
            (1, 'Lean Software Development: An Agile Toolkit', 240, 4.17, '9780320000000', '2003-05-18', 5),
            (2, 'Facing the Intelligence Explosion', 91, 3.87, null, '2013-02-01', 7),
            (4, 'Patterns of Software: Tales from the Software Community', 256, 3.84, '9780200000000', '1996-08-15', 1),
            (5, 'Anatomy Of LISP', 446, 4.43, '9780070000000', '1978-01-01', 3),
            (6, 'Computing machinery and intelligence', 24, 4.17, null, '2009-03-22', 4),
            (7, 'XML: Visual QuickStart Guide', 269, 3.66, '9780320000000', '2009-01-01', 5),
            (8, 'SQL Cookbook', 595, 3.95, '9780600000000', '2005-12-01', 7),
            (9, 'The Apollo Guidance Computer: Architecture And Operation (Springer Praxis Books / Space Exploration)', 439, 4.29, '9781440000000', '2010-07-01', 6),
            (10, 'Minds and Computers: An Introduction to the Philosophy of Artificial Intelligence', 222, 3.54, '9780750000000', '2007-02-13', 7);                                                     
        """))

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "books_pkey"
DETAIL:  Key (book_id)=(1) already exists.

[SQL:
        INSERT INTO publishers (publisher_id, name) VALUES
        (1, 'O Reilly Media'),
        (2, 'A Book Apart'),
        (3, 'A K PETERS'),
        (4, 'Academic Press'),
        (5, 'Addison Wesley'),
        (6, 'Albert&Sweigart'),
        (7, 'Alfred A. Knopf')
    ON CONFLICT (publisher_id) DO NOTHING;
    INSERT INTO authors (author_id, first_name, middle_name, last_name) VALUES
        (1, 'Merritt', NULL, 'Eric'),
        (2, 'Linda', NULL, 'Mui'),
        (3, 'Alecos', NULL, 'Papadatos'),
        (4, 'Anthony', NULL, 'Molinaro'),
        (5, 'David', NULL, 'Cronin'),
        (6, 'Richard', NULL, 'Blum'),
        (7, 'Yuval', 'Noah', 'Harari'),
        (8, 'Paul', NULL, 'Albitz')
    ON CONFLICT (author_id) DO NOTHING;
    INSERT INTO books (book_id, title, total_pages, rating, isbn, published_date, publisher_id) VALUES
            (1, 'Lean Software Development: An Agile Toolkit', 240, 4.17, '9780320000000', '2003-05-18', 5),
            (2, 'Facing the Intelligence Explosion', 91, 3.87, null, '2013-02-01', 7),
            (4, 'Patterns of Software: Tales from the Software Community', 256, 3.84, '9780200000000', '1996-08-15', 1),
            (5, 'Anatomy Of LISP', 446, 4.43, '9780070000000', '1978-01-01', 3),
            (6, 'Computing machinery and intelligence', 24, 4.17, null, '2009-03-22', 4),
            (7, 'XML: Visual QuickStart Guide', 269, 3.66, '9780320000000', '2009-01-01', 5),
            (8, 'SQL Cookbook', 595, 3.95, '9780600000000', '2005-12-01', 7),
            (9, 'The Apollo Guidance Computer: Architecture And Operation (Springer Praxis Books / Space Exploration)', 439, 4.29, '9781440000000', '2010-07-01', 6),
            (10, 'Minds and Computers: An Introduction to the Philosophy of Artificial Intelligence', 222, 3.54, '9780750000000', '2007-02-13', 7);
        ]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [6]:
df = pd.read_sql(""" SELECT author_id, Title, isbn
                    FROM books
                    INNER JOIN book_authors ON books.book_id = book_authors.book_id;""", engine);
df

   author_id                                              title           isbn
0          1        Lean Software Development: An Agile Toolkit  9780320000000
1          8                  Facing the Intelligence Explosion           None
2          7                                    Scala in Action  9781940000000
3          6  Patterns of Software: Tales from the Software ...  9780200000000
4          5                                    Anatomy Of LISP  9780070000000
5          4               Computing machinery and intelligence           None
6          3                       XML: Visual QuickStart Guide  9780320000000
7          2                                       SQL Cookbook  9780600000000
8          4  The Apollo Guidance Computer: Architecture And...  9781440000000
9          1  Minds and Computers: An Introduction to the Ph...  9780750000000

In [16]:
df = pd.read_sql(""" SELECT publishers.name, books.book_id
                        FROM publishers
                        LEFT JOIN books ON publishers.publisher_id = books.publisher_id
                        ORDER BY publishers.name;""", engine);
df

               name  book_id
0      A Book Apart      NaN
1        A K PETERS      5.0
2    Academic Press      6.0
3    Addison Wesley      7.0
4    Addison Wesley      1.0
5   Albert&Sweigart      9.0
6   Alfred A. Knopf      2.0
7   Alfred A. Knopf      8.0
8   Alfred A. Knopf     10.0
9    O Reilly Media      4.0
10   O Reilly Media      3.0

In [19]:
df = pd.read_sql(""" SELECT * FROM Publishers
                     WHERE name LIKE 'A%';""", engine);
df

TypeError: sqlalchemy.cyextension.immutabledict.immutabledict is not a sequence